import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    slug: "oura-ring-gen3",
    title: "Oura Ring Gen 3",
    vendor: "oura",
    affiliateUrl: "https://ouraring.com?utm_source=acme",
    images: ["/oura-ring-gen3-silver-black-wearable-smart-ring.jpg"],
    price: 299,
    priceInCents: 29900, // $299.00
    currency: "USD",
    rating: 4.7,
    category: "wearables",
    goals: ["sleep", "hrv", "recovery"],
    tags: ["wearable", "sleep-tracking", "hrv", "recovery"],
    stockStatus: "in_stock",
    short: "Advanced sleep and recovery tracking ring with detailed HRV and readiness metrics.",
    pros: ["Excellent sleep tracking", "Comfortable 24/7 wear", "Long battery life"],
    cons: ["Requires subscription", "No real-time workout tracking"],
    createdAt: "2024-01-15",
    popularity: 95,
  },
  {
    id: "2",
    slug: "whoop-4-0",
    title: "WHOOP 4.0",
    vendor: "whoop",
    affiliateUrl: "https://whoop.com?utm_source=acme",
    images: ["/whoop-4-0-fitness-tracker-band-black-wearable.jpg"],
    price: 239,
    priceInCents: 23900,
    currency: "USD",
    rating: 4.5,
    category: "wearables",
    goals: ["recovery", "hrv", "sleep"],
    tags: ["wearable", "recovery", "strain", "hrv"],
    stockStatus: "in_stock",
    short: "Subscription-based recovery and strain tracker for optimizing training and rest.",
    pros: ["Detailed recovery metrics", "No screen distractions", "Waterproof"],
    cons: ["Requires ongoing subscription", "No display"],
    createdAt: "2024-02-20",
    popularity: 88,
  },
  {
    id: "3",
    slug: "eight-sleep-pod-4",
    title: "Eight Sleep Pod 4",
    vendor: "eight_sleep",
    affiliateUrl: "https://eightsleep.com?utm_source=acme",
    images: ["/eight-sleep-pod-smart-mattress-bed-temperature-con.jpg"],
    price: 2695,
    priceInCents: 269500,
    currency: "USD",
    rating: 4.8,
    category: "sleep",
    goals: ["sleep", "recovery"],
    tags: ["smart-mattress", "temperature-control", "sleep-optimization"],
    stockStatus: "in_stock",
    short: "Smart mattress with dynamic temperature control for optimal sleep quality.",
    pros: ["Precise temperature control", "Excellent sleep tracking", "Dual-zone"],
    cons: ["Very expensive", "Requires subscription for features"],
    createdAt: "2024-03-10",
    popularity: 82,
  },
  {
    id: "4",
    slug: "levels-continuous-glucose-monitor",
    title: "Levels CGM Program",
    vendor: "levels",
    affiliateUrl: "https://levelshealth.com?utm_source=acme",
    images: ["/continuous-glucose-monitor-sensor-arm-patch-health.jpg"],
    price: 399,
    priceInCents: 39900,
    currency: "USD",
    rating: 4.6,
    category: "diagnostics",
    goals: ["metabolic", "longevity"],
    tags: ["cgm", "metabolic-health", "glucose", "nutrition"],
    stockStatus: "in_stock",
    short: "Continuous glucose monitoring program to optimize metabolic health and energy.",
    pros: ["Real-time glucose insights", "Personalized recommendations", "Easy to use"],
    cons: ["Ongoing sensor costs", "Not covered by insurance"],
    createdAt: "2023-11-05",
    popularity: 79,
  },
  {
    id: "5",
    slug: "thorne-multi-vitamin-elite",
    title: "Thorne Multi-Vitamin Elite",
    vendor: "thorne",
    affiliateUrl: "https://thorne.com?utm_source=acme",
    images: ["/thorne-multivitamin-supplement-bottle-pills.jpg"],
    price: 58,
    priceInCents: 5800,
    currency: "USD",
    rating: 4.7,
    category: "nutrition",
    goals: ["longevity", "cognitive", "recovery"],
    tags: ["supplement", "vitamins", "foundational"],
    stockStatus: "in_stock",
    short: "Comprehensive multivitamin designed for active individuals and athletes.",
    pros: ["High-quality ingredients", "Bioavailable forms", "NSF certified"],
    cons: ["Multiple pills per serving", "Premium price"],
    createdAt: "2023-09-18",
    popularity: 90,
  },
  {
    id: "6",
    slug: "momentous-omega-3",
    title: "Momentous Omega-3",
    vendor: "shopify",
    affiliateUrl: "https://livemomentous.com?utm_source=acme",
    images: ["/momentous-omega-3-fish-oil-supplement-capsules-bot.jpg"],
    price: 45,
    priceInCents: 4500,
    currency: "USD",
    rating: 4.8,
    category: "nutrition",
    goals: ["longevity", "cognitive", "recovery"],
    tags: ["supplement", "omega-3", "heart-health", "brain-health"],
    stockStatus: "in_stock",
    short: "High-purity omega-3 supplement for heart, brain, and inflammation support.",
    pros: ["Third-party tested", "High EPA/DHA", "No fishy aftertaste"],
    cons: ["Requires daily consistency"],
    createdAt: "2024-01-08",
    popularity: 86,
  },
  {
    id: "7",
    slug: "lifespan-book-david-sinclair",
    title: "Lifespan: Why We Age",
    vendor: "amazon",
    vendorProductId: "B07N4C6LGR",
    affiliateUrl: "https://amazon.com/dp/B07N4C6LGR?tag=acme-20",
    images: ["/lifespan-book-cover-david-sinclair-aging-science.jpg"],
    price: 18,
    priceInCents: 1800,
    currency: "USD",
    rating: 4.6,
    category: "books",
    goals: ["longevity"],
    tags: ["education", "science", "longevity-research"],
    stockStatus: "in_stock",
    short: "Revolutionary book on aging science by Harvard researcher David Sinclair.",
    pros: ["Evidence-based", "Easy to understand", "Actionable insights"],
    cons: ["Some controversial claims"],
    createdAt: "2023-08-12",
    popularity: 92,
  },
  {
    id: "8",
    slug: "apollo-neuro-wearable",
    title: "Apollo Neuro",
    vendor: "other",
    affiliateUrl: "https://apolloneuro.com?utm_source=acme",
    images: ["/apollo-neuro-wearable-band-stress-relief-device.jpg"],
    price: 349,
    priceInCents: 34900,
    currency: "USD",
    rating: 4.4,
    category: "wearables",
    goals: ["recovery", "sleep", "cognitive"],
    tags: ["wearable", "stress-management", "vagal-tone"],
    stockStatus: "in_stock",
    short: "Wearable that uses gentle vibrations to improve stress resilience and sleep.",
    pros: ["Drug-free stress relief", "Improves HRV", "Discreet"],
    cons: ["Results take time", "Premium price"],
    createdAt: "2023-12-01",
    popularity: 71,
  },
  {
    id: "9",
    slug: "hatch-restore-2",
    title: "Hatch Restore 2",
    vendor: "amazon",
    vendorProductId: "B0BW7T8MQJ",
    affiliateUrl: "https://amazon.com/dp/B0BW7T8MQJ?tag=acme-20",
    images: ["/hatch-restore-smart-alarm-clock-sunrise-light.jpg"],
    price: 169,
    priceInCents: 16900,
    currency: "USD",
    rating: 4.5,
    category: "sleep",
    goals: ["sleep"],
    tags: ["smart-alarm", "light-therapy", "sleep-routine"],
    stockStatus: "in_stock",
    short: "Smart alarm clock with sunrise simulation and wind-down routines.",
    pros: ["Helps sleep routine", "Beautiful design", "Easy to use"],
    cons: ["Requires subscription for content", "Limited customization"],
    createdAt: "2024-02-14",
    popularity: 84,
  },
  {
    id: "10",
    slug: "athletic-greens-ag1",
    title: "AG1 by Athletic Greens",
    vendor: "other",
    affiliateUrl: "https://athleticgreens.com?utm_source=acme",
    images: ["/athletic-greens-ag1-supplement-powder-canister-gre.jpg"],
    price: 99,
    priceInCents: 9900,
    currency: "USD",
    rating: 4.6,
    category: "nutrition",
    goals: ["longevity", "cognitive", "recovery"],
    tags: ["supplement", "greens", "foundational", "gut-health"],
    stockStatus: "in_stock",
    short: "All-in-one nutritional supplement with 75 vitamins, minerals, and whole foods.",
    pros: ["Comprehensive nutrition", "Convenient", "Good taste"],
    cons: ["Expensive", "Contains many ingredients"],
    createdAt: "2023-10-22",
    popularity: 93,
  },
  {
    id: "11",
    slug: "muse-s-headband",
    title: "Muse S Headband",
    vendor: "amazon",
    vendorProductId: "B08696J4MR",
    affiliateUrl: "https://amazon.com/dp/B08696J4MR?tag=acme-20",
    images: ["/muse-s-headband-meditation-eeg-sleep-tracking.jpg"],
    price: 399,
    priceInCents: 39900,
    currency: "USD",
    rating: 4.3,
    category: "wearables",
    goals: ["cognitive", "sleep", "recovery"],
    tags: ["meditation", "neurofeedback", "brain-training"],
    stockStatus: "in_stock",
    short: "EEG headband for meditation training and sleep tracking with real-time feedback.",
    pros: ["Real-time meditation feedback", "Sleep tracking", "Backed by research"],
    cons: ["Learning curve", "Must wear during meditation"],
    createdAt: "2023-11-30",
    popularity: 68,
  },
  {
    id: "12",
    slug: "vital-proteins-collagen",
    title: "Vital Proteins Collagen",
    vendor: "amazon",
    vendorProductId: "B00K6JUG7K",
    affiliateUrl: "https://amazon.com/dp/B00K6JUG7K?tag=acme-20",
    images: ["/vital-proteins-collagen-peptides-powder-blue-canis.jpg"],
    price: 47,
    priceInCents: 4700,
    currency: "USD",
    rating: 4.7,
    category: "nutrition",
    goals: ["longevity", "recovery"],
    tags: ["supplement", "collagen", "skin", "joints"],
    stockStatus: "in_stock",
    short: "Grass-fed collagen peptides for skin, hair, nails, and joint support.",
    pros: ["High quality", "Mixes easily", "Tasteless"],
    cons: ["Daily commitment needed"],
    createdAt: "2023-07-19",
    popularity: 89,
  },
  {
    id: "13",
    slug: "breathwork-app-subscription",
    title: "Othership Breathwork",
    vendor: "other",
    affiliateUrl: "https://othership.us?utm_source=acme",
    images: ["/othership-breathwork-app-interface-meditation-brea.jpg"],
    price: 99,
    priceInCents: 9900,
    currency: "USD",
    rating: 4.8,
    category: "smart_home",
    goals: ["recovery", "cognitive", "hrv"],
    tags: ["app", "breathwork", "stress-management"],
    stockStatus: "in_stock",
    short: "Guided breathwork app with sessions for energy, focus, and recovery.",
    pros: ["Variety of protocols", "Great instructors", "Improves HRV"],
    cons: ["Annual subscription"],
    createdAt: "2024-01-25",
    popularity: 76,
  },
  {
    id: "14",
    slug: "theragun-pro",
    title: "Theragun PRO",
    vendor: "amazon",
    vendorProductId: "B08F9Y3YPZ",
    affiliateUrl: "https://amazon.com/dp/B08F9Y3YPZ?tag=acme-20",
    images: ["/theragun-pro-massage-gun-recovery-device-black.jpg"],
    price: 599,
    priceInCents: 59900,
    currency: "USD",
    rating: 4.7,
    category: "smart_home",
    goals: ["recovery"],
    tags: ["recovery-tool", "massage", "muscle"],
    stockStatus: "in_stock",
    short: "Professional-grade percussion therapy device for muscle recovery.",
    pros: ["Very powerful", "Multiple attachments", "Quiet operation"],
    cons: ["Expensive", "Heavy"],
    createdAt: "2023-09-05",
    popularity: 85,
  },
  {
    id: "15",
    slug: "nutrisense-cgm-program",
    title: "NutriSense CGM",
    vendor: "other",
    affiliateUrl: "https://nutrisense.io?utm_source=acme",
    images: ["/nutrisense-cgm-sensor-glucose-monitor-arm.jpg"],
    price: 299,
    priceInCents: 29900,
    currency: "USD",
    rating: 4.5,
    category: "diagnostics",
    goals: ["metabolic", "longevity"],
    tags: ["cgm", "nutrition", "metabolic-health"],
    stockStatus: "in_stock",
    short: "CGM program with dietitian support for optimizing metabolic health.",
    pros: ["Professional guidance", "Detailed insights", "App integration"],
    cons: ["Monthly sensor costs", "Learning curve"],
    createdAt: "2023-10-10",
    popularity: 74,
  },
  {
    id: "16",
    slug: "outlive-book-peter-attia",
    title: "Outlive: The Science of Longevity",
    vendor: "amazon",
    vendorProductId: "B0B1BTJLJN",
    affiliateUrl: "https://amazon.com/dp/B0B1BTJLJN?tag=acme-20",
    images: ["/placeholder.svg?height=400&width=400"],
    price: 20,
    priceInCents: 2000,
    currency: "USD",
    rating: 4.8,
    category: "books",
    goals: ["longevity"],
    tags: ["education", "health-optimization", "longevity"],
    stockStatus: "in_stock",
    short: "Comprehensive guide to longevity and healthspan by Dr. Peter Attia.",
    pros: ["Evidence-based", "Actionable strategies", "Well-researched"],
    cons: ["Dense reading"],
    createdAt: "2023-06-14",
    popularity: 96,
  },
  {
    id: "17",
    slug: "lmnt-electrolytes",
    title: "LMNT Electrolytes",
    vendor: "other",
    affiliateUrl: "https://drinklmnt.com?utm_source=acme",
    images: ["/placeholder.svg?height=400&width=400"],
    price: 45,
    priceInCents: 4500,
    currency: "USD",
    rating: 4.7,
    category: "nutrition",
    goals: ["recovery", "metabolic"],
    tags: ["hydration", "electrolytes", "keto-friendly"],
    stockStatus: "in_stock",
    short: "Sugar-free electrolyte drink mix optimized for hydration and performance.",
    pros: ["No sugar", "High sodium", "Great flavors"],
    cons: ["Saltier than typical sports drinks"],
    createdAt: "2024-03-02",
    popularity: 87,
  },
  {
    id: "18",
    slug: "joovv-red-light-therapy",
    title: "Joovv Mini",
    vendor: "other",
    affiliateUrl: "https://joovv.com?utm_source=acme",
    images: ["/placeholder.svg?height=400&width=400"],
    price: 699,
    priceInCents: 69900,
    currency: "USD",
    rating: 4.6,
    category: "smart_home",
    goals: ["recovery", "longevity"],
    tags: ["red-light-therapy", "recovery", "cellular-health"],
    stockStatus: "in_stock",
    short: "Medical-grade red light therapy device for cellular health and recovery.",
    pros: ["Clinical-grade", "Easy to use", "Well-researched benefits"],
    cons: ["Expensive", "Requires daily use"],
    createdAt: "2023-08-28",
    popularity: 73,
  },
]
